CREATE PROCEDURE [dbo].[TituloEliminar]
	@Id_Titulo INT
AS
	BEGIN
		SET NOCOUNT ON
		BEGIN TRANSACTION TRASA
		BEGIN TRY

			DELETE FROM Titulos
			WHERE Id_Titulo = @Id_Titulo
			
			COMMIT TRANSACTION
			
			SELECT 0 AS CodeError, '' AS msgError
		END TRY
		BEGIN CATCH
			SELECT
				ERROR_NUMBER() AS CodeError
				, ERROR_NUMBER() AS MsgError
			ROLLBACK TRANSACTION TRASA
		END CATCH

	END
